apply plugin: 'com.android.library'
apply from: '../shared/keepUnitySymbols.gradle'
apply from: '../shared/common.gradle'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'androidx.recyclerview:recyclerview:1.2.1' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:9
    implementation 'com.android.support:customtabs:28.+' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:7
    implementation 'com.android.support:recyclerview-v7:28.+' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:6
    implementation 'com.applovin.mediation:bidmachine-adapter:3.6.1.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/BidMachine/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:bigoads-adapter:5.8.2.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/BigoAds/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:bytedance-adapter:7.9.1.3.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/ByteDance/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:facebook-adapter:[6.16.0.0]' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Facebook/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:fyber-adapter:8.4.5.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Fyber/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:google-adapter:[25.2.0.0]' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Google/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:google-ad-manager-adapter:[25.2.0.0]' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/GoogleAdManager/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:inmobi-adapter:11.2.0.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:ironsource-adapter:9.4.1.0.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/IronSource/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:mintegral-adapter:17.1.51.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:moloco-adapter:4.8.0.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Moloco/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:smaato-adapter:22.7.2.3' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Smaato/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:unityads-adapter:4.17.0.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/UnityAds/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:verve-adapter:3.7.1.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Verve/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:vungle-adapter:7.7.3.1' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Vungle/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:yandex-adapter:7.18.5.0' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/Yandex/Editor/Dependencies.xml:4
    implementation 'com.applovin:applovin-sdk:13.6.3' // Assets/PTITGameSDK/ThirdParty/MaxSdk/AppLovin/Editor/Dependencies.xml:4
    implementation 'com.google.android.gms:play-services-ads-identifier:18.1.0' // Assets/LevelPlay/Editor/IronSourceSDKDependencies.xml:12
    implementation 'com.google.android.gms:play-services-base:18.10.1' // Assets/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.firebase:firebase-analytics:23.2.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:18
    implementation 'com.google.firebase:firebase-analytics-unity:13.17.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:21
    implementation 'com.google.firebase:firebase-app-unity:13.17.0' // Assets/Firebase/Editor/AppDependencies.xml:25
    implementation 'com.google.firebase:firebase-common:22.2.1' // Assets/Firebase/Editor/AppDependencies.xml:16
    implementation 'com.google.firebase:firebase-config:23.1.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:16
    implementation 'com.google.firebase:firebase-config-unity:13.17.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:23
    implementation 'com.squareup.picasso:picasso:2.71828' // Assets/PTITGameSDK/ThirdParty/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:5
    implementation 'com.unity3d.ads:unity-ads:4.21.0' // Assets/LevelPlay/Editor/ISUnityAdsAdapterDependencies.xml:9
    implementation 'com.unity3d.ads-mediation:mediation-sdk:9.6.1' // Assets/LevelPlay/Editor/IronSourceSDKDependencies.xml:5
    implementation 'com.unity3d.ads-mediation:unityads-adapter:5.14.0' // Assets/LevelPlay/Editor/ISUnityAdsAdapterDependencies.xml:5
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packaging {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/armeabi-v7a/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    namespace "com.unity3d.player"
    ndkPath "**NDKPATH**"
    ndkVersion "**NDKVERSION**"

    compileSdk **APIVERSION**
    buildToolsVersion = "**BUILDTOOLS**"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk **MINSDK**
        targetSdk **TARGETSDK**
        ndk {
            abiFilters **ABIFILTERS**
            debugSymbolLevel **DEBUGSYMBOLLEVEL**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
**DEFAULT_CONFIG_SETUP**
    }

    lint {
        abortOnError false
    }

    androidResources {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**
